Error Time: 2024-12-29-11-43-25
Error Message: 更新检查时数据解析出错: Expecting value: line 1 column 1 (char 0)
Traceback:
Traceback (most recent call last):
  File "UI.py", line 66, in check_for_updates
  File "pyupdater\client\__init__.py", line 213, in __init__
  File "pyupdater\client\__init__.py", line 217, in refresh
  File "pyupdater\client\__init__.py", line 368, in _get_signing_key
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
